<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>FOA-SDK-ControlPanel</AssemblyName>
    <RootNamespace>FOA.SDK.ControlPanel</RootNamespace>
    <StartupObject>FOA.SDK.ControlPanel.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>..\..\..\TaintedGrailModdingEditor\TaintedGrailModdingEditor.ico</ApplicationIcon>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>embedded</DebugType>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)/bin/**;$(MSBuildProjectDirectory)/obj/**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Providers\foa.provider.json" LogicalName="FOA.SDK.ControlPanel.Providers.foa.provider.json" />
  </ItemGroup>
</Project>
