param([string]$Request="",[string[]]$TargetPath=@(),[switch]$AsJson)
$ErrorActionPreference='Stop'
$combined=(($Request,($TargetPath -join ' '))-join ' ').ToLowerInvariant()
$surfaces=New-Object 'System.Collections.Generic.List[string]';$reasons=New-Object 'System.Collections.Generic.List[string]';$warnings=New-Object 'System.Collections.Generic.List[string]'
function Add-U($l,$v){if(-not $l.Contains($v)){[void]$l.Add($v)}}
if($combined -match 'tick|event|ebus|component|systemcomponent'){Add-U $surfaces 'O3DE component, event, or bus path';Add-U $reasons 'Frequently invoked host paths can affect broad editor state.'}
if($combined -match 'ui|qt|widget|pane|render|binding|model'){Add-U $surfaces 'Editor UI render or binding';Add-U $reasons 'UI refresh paths can allocate or recompute repeatedly.'}
if($combined -match 'asset|catalog|scan|workspace|pack|foreach|loop|linq|tolist|where|select'){Add-U $surfaces 'Large collection, catalog, or asset scan';Add-U $reasons 'Repository, asset, catalog, and workspace scans can become unbounded.'}
if($combined -match 'file|json|xml|serialize|interchange|log|process|unity|conversion|installer|package'){Add-U $surfaces 'IO, serialization, external process, conversion, or package path';Add-U $reasons 'IO and external work must remain bounded and off interactive hot paths.'}
if($combined -match 'reflection|dynamic|plugin|extensionapi|adapter|bepinex|mono|il2cpp'){Add-U $surfaces 'Dynamic registration or adapter path';Add-U $reasons 'Dynamic discovery and adapter hooks can become expensive or invasive.'}
if($surfaces.Count -eq 0){Add-U $surfaces 'Unclassified';Add-U $warnings 'No surface classified. Identify owner paths before editing.'}
$risk='Low';if($surfaces.Count -gt 1 -or $combined -match 'tick|render|binding|scan|conversion|installer|adapter|runtime'){ $risk='High' } elseif($surfaces[0] -ne 'Unclassified'){ $risk='Medium' }
$forbidden=@('No heavy invasive unnecessary code.','No broad refactor, architecture rewrite, dependency addition, or public contract change without authority.','No unbounded scans on editor tick, render, serialization, command, process, or event paths.','No repeated reflection, file IO, external-process discovery, parsing, or logging inside loops or hot paths.','No repeated allocation-heavy transforms or accidental O(N^2) work without measurement.','No hidden state repair, opportunistic migration, or stale-truth cache.','No performance claim from configure or compile success.')
$checks=@('Run Release/Profile builds and targeted owner tests.','Audit changed hot paths for allocation, scans, reflection, IO, logging, blocking, and complexity.','State before/after complexity and representative data cardinality.','For High risk, run or add a deterministic performance guard with a named threshold.','For UI, prove refresh work is bounded and does not recompute domain truth.','For external tools and conversion, prove timeouts, output bounds, cancellation, and process cleanup.','For adapters, prove detection and hooks are cached and minimal.','Report missing guards or measurements as partial/blocked.')
$evidence=@('Performance risk and surfaces.','Hot-path audit findings.','Baseline or researched expected cost.','Threshold, measured result, command, configuration, and machine/editor/toolchain/runtime context.','Complexity and cardinality statement.','Missing lanes reported as partial/blocked.')
$result=[ordered]@{request=$Request;target_paths=$TargetPath;changed_surfaces=@($surfaces);performance_risk=$risk;risk_reasons=@($reasons);forbidden_shortcuts=$forbidden;required_hard_performance_checks=$checks;required_evidence=$evidence;warnings=@($warnings)}
if($AsJson){$result|ConvertTo-Json -Depth 5;return}
'FOA-SDK professional code and performance preflight';'===================================================';"Request: $Request";'';'Changed surfaces:';$surfaces|%{"- $_"};'';"Performance risk: $risk";'';'Risk reasons:';if($reasons.Count){$reasons|%{"- $_"}}else{'- No specific hot path detected.'};'';'Forbidden shortcuts:';$forbidden|%{"- $_"};'';'Required hard performance checks:';$checks|%{"- $_"};'';'Required evidence:';$evidence|%{"- $_"};if($warnings.Count){'';'Warnings:';$warnings|%{"- $_"}}
